# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

source 'https://github.com/CocoaPods/Specs.git'

target "cyclecity" do
	pod 'AFNetworking'
	pod 'UICKeyChainStore'
	pod 'Mapbox-iOS-SDK'
end

target "cyclecityTests" do

end

