-- MySQL Script generated by MySQL Workbench
-- Mon Oct  6 22:36:23 2014
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cyclecity
-- -----------------------------------------------------
-- Base de donnée de l’API cyclecity

-- -----------------------------------------------------
-- Schema cyclecity
--
-- Base de donnée de l’API cyclecity
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cyclecity` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `cyclecity` ;

-- -----------------------------------------------------
-- Table `cyclecity`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cyclecity`.`utilisateur` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(70) NULL,
  `mdp` VARCHAR(70) NULL,
  `nom` VARCHAR(70) NULL,
  `prenom` VARCHAR(70) NULL,
  `en_ligne` TINYINT(1) NULL,
  `velo` VARCHAR(70) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cyclecity`.`trajet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cyclecity`.`trajet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `heure_debut` DATETIME NULL,
  `heure_fin` DATETIME NULL,
  `distance` INT NULL,
  `vitesse_max` INT NULL,
  `vitesse_moyenne` INT NULL,
  `utilisateur_id` INT NOT NULL,
  PRIMARY KEY (`id`, `utilisateur_id`),
  INDEX `fk_trajet_utilisateur_idx` (`utilisateur_id` ASC),
  CONSTRAINT `fk_trajet_utilisateur`
    FOREIGN KEY (`utilisateur_id`)
    REFERENCES `cyclecity`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cyclecity`.`noeud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cyclecity`.`noeud` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `latitude` DOUBLE NULL,
  `longitude` DOUBLE NULL,
  `heure` DATETIME NULL,
  `trajet_id` INT NOT NULL,
  `trajet_utilisateur_id` INT NOT NULL,
  PRIMARY KEY (`id`, `trajet_id`, `trajet_utilisateur_id`),
  INDEX `fk_noeud_trajet1_idx` (`trajet_id` ASC, `trajet_utilisateur_id` ASC),
  CONSTRAINT `fk_noeud_trajet1`
    FOREIGN KEY (`trajet_id` , `trajet_utilisateur_id`)
    REFERENCES `cyclecity`.`trajet` (`id` , `utilisateur_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cyclecity`.`stat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cyclecity`.`stat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `vitesse_max` INT NULL,
  `utilisateur_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_stats_utilisateur1_idx` (`utilisateur_id` ASC),
  CONSTRAINT `fk_stats_utilisateur1`
    FOREIGN KEY (`utilisateur_id`)
    REFERENCES `cyclecity`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `cyclecity`.`trajet_favori`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cyclecity`.`trajet_favori` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `trajet_id` INT NOT NULL,
  `trajet_utilisateur_id` INT NOT NULL,
  PRIMARY KEY (`id`, `trajet_id`, `trajet_utilisateur_id`),
  INDEX `fk_trajet_favori_trajet1_idx` (`trajet_id` ASC, `trajet_utilisateur_id` ASC),
  CONSTRAINT `fk_trajet_favori_trajet1`
    FOREIGN KEY (`trajet_id` , `trajet_utilisateur_id`)
    REFERENCES `cyclecity`.`trajet` (`id` , `utilisateur_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cyclecity`.`ami`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cyclecity`.`ami` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `utilisateur_id` INT NOT NULL,
  PRIMARY KEY (`id`, `utilisateur_id`),
  INDEX `fk_ami_utilisateur1_idx` (`utilisateur_id` ASC),
  CONSTRAINT `fk_ami_utilisateur1`
    FOREIGN KEY (`utilisateur_id`)
    REFERENCES `cyclecity`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
